spring:
  application:
    name: springbootplay

  datasource:
    url: jdbc:mysql://localhost:3306/players
    username: appuser
    password: mypassword

  flyway:
    enabled: true
    baseline-on-migrate: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

management:
  endpoints:
    web:
      exposure:
        include: health,flyway