ALTER TABLE player
    ADD COLUMN AI_SUMMARY TEXT NULL,
    ADD COLUMN UPDATED_AT TIMESTAMP NULL;

ALTER TABLE audit_log
    ADD COLUMN ACTION VARCHAR(30) NOT NULL DEFAULT 'CREATED',
    ADD COLUMN CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DROP COLUMN AGE,
    DROP COLUMN POSITION;
